<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \DB::table('paises')->insert([
            ['id' => 1, 'iso' => 'AF', 'nombre' => 'Afganistán'],
            ['id' => 2, 'iso' => 'AX', 'nombre' => 'Islas Gland'],
            ['id' => 3, 'iso' => 'AL', 'nombre' => 'Albania'],
            ['id' => 4, 'iso' => 'DE', 'nombre' => 'Alemania'],
            ['id' => 5, 'iso' => 'AD', 'nombre' => 'Andorra'],
            ['id' => 6, 'iso' => 'AO', 'nombre' => 'Angola'],
            ['id' => 7, 'iso' => 'AI', 'nombre' => 'Anguilla'],
            ['id' => 8, 'iso' => 'AQ', 'nombre' => 'Antártida'],
            ['id' => 9, 'iso' => 'AG', 'nombre' => 'Antigua y Barbuda'],
            ['id' => 10, 'iso' => 'AN', 'nombre' => 'Antillas Holandesas'],
            ['id' => 11, 'iso' => 'SA', 'nombre' => 'Arabia Saudí'],
            ['id' => 12, 'iso' => 'DZ', 'nombre' => 'Argelia'],
            ['id' => 13, 'iso' => 'AR', 'nombre' => 'Argentina'],
            ['id' => 14, 'iso' => 'AM', 'nombre' => 'Armenia'],
            ['id' => 15, 'iso' => 'AW', 'nombre' => 'Aruba'],
            ['id' => 16, 'iso' => 'AU', 'nombre' => 'Australia'],
            ['id' => 17, 'iso' => 'AT', 'nombre' => 'Austria'],
            ['id' => 18, 'iso' => 'AZ', 'nombre' => 'Azerbaiyán'],
            ['id' => 19, 'iso' => 'BS', 'nombre' => 'Bahamas'],
            ['id' => 20, 'iso' => 'BH', 'nombre' => 'Bahréin'],
            ['id' => 21, 'iso' => 'BD', 'nombre' => 'Bangladesh'],
            ['id' => 22, 'iso' => 'BB', 'nombre' => 'Barbados'],
            ['id' => 23, 'iso' => 'BY', 'nombre' => 'Bielorrusia'],
            ['id' => 24, 'iso' => 'BE', 'nombre' => 'Bélgica'],
            ['id' => 25, 'iso' => 'BZ', 'nombre' => 'Belice'],
            ['id' => 26, 'iso' => 'BJ', 'nombre' => 'Benin'],
            ['id' => 27, 'iso' => 'BM', 'nombre' => 'Bermudas'],
            ['id' => 28, 'iso' => 'BT', 'nombre' => 'Bhután'],
            ['id' => 29, 'iso' => 'BO', 'nombre' => 'Bolivia'],
            ['id' => 30, 'iso' => 'BA', 'nombre' => 'Bosnia y Herzegovina'],
            ['id' => 31, 'iso' => 'BW', 'nombre' => 'Botsuana'],
            ['id' => 32, 'iso' => 'BV', 'nombre' => 'Isla Bouvet'],
            ['id' => 33, 'iso' => 'BR', 'nombre' => 'Brasil'],
            ['id' => 34, 'iso' => 'BN', 'nombre' => 'Brunéi'],
            ['id' => 35, 'iso' => 'BG', 'nombre' => 'Bulgaria'],
            ['id' => 36, 'iso' => 'BF', 'nombre' => 'Burkina Faso'],
            ['id' => 37, 'iso' => 'BI', 'nombre' => 'Burundi'],
            ['id' => 38, 'iso' => 'CV', 'nombre' => 'Cabo Verde'],
            ['id' => 39, 'iso' => 'KY', 'nombre' => 'Islas Caimán'],
            ['id' => 40, 'iso' => 'KH', 'nombre' => 'Camboya'],
            ['id' => 41, 'iso' => 'CM', 'nombre' => 'Camerún'],
            ['id' => 42, 'iso' => 'CA', 'nombre' => 'Canadá'],
            ['id' => 43, 'iso' => 'CF', 'nombre' => 'República Centroafricana'],
            ['id' => 44, 'iso' => 'TD', 'nombre' => 'Chad'],
            ['id' => 45, 'iso' => 'CZ', 'nombre' => 'República Checa'],
            ['id' => 46, 'iso' => 'CL', 'nombre' => 'Chile'],
            ['id' => 47, 'iso' => 'CN', 'nombre' => 'China'],
            ['id' => 48, 'iso' => 'CY', 'nombre' => 'Chipre'],
            ['id' => 49, 'iso' => 'CX', 'nombre' => 'Isla de Navidad'],
            ['id' => 50, 'iso' => 'VA', 'nombre' => 'Ciudad del Vaticano'],
            ['id' => 51, 'iso' => 'CC', 'nombre' => 'Islas Cocos'],
            ['id' => 52, 'iso' => 'CO', 'nombre' => 'Colombia'],
            ['id' => 53, 'iso' => 'KM', 'nombre' => 'Comoras'],
            ['id' => 54, 'iso' => 'CD', 'nombre' => 'República Democrática del Congo'],
            ['id' => 55, 'iso' => 'CG', 'nombre' => 'Congo'],
            ['id' => 56, 'iso' => 'CK', 'nombre' => 'Islas Cook'],
            ['id' => 57, 'iso' => 'KP', 'nombre' => 'Corea del Norte'],
            ['id' => 58, 'iso' => 'KR', 'nombre' => 'Corea del Sur'],
            ['id' => 59, 'iso' => 'CI', 'nombre' => 'Costa de Marfil'],
            ['id' => 60, 'iso' => 'CR', 'nombre' => 'Costa Rica'],
            ['id' => 61, 'iso' => 'HR', 'nombre' => 'Croacia'],
            ['id' => 62, 'iso' => 'CU', 'nombre' => 'Cuba'],
            ['id' => 63, 'iso' => 'DK', 'nombre' => 'Dinamarca'],
            ['id' => 64, 'iso' => 'DM', 'nombre' => 'Dominica'],
            ['id' => 65, 'iso' => 'DO', 'nombre' => 'República Dominicana'],
            ['id' => 66, 'iso' => 'EC', 'nombre' => 'Ecuador'],
            ['id' => 67, 'iso' => 'EG', 'nombre' => 'Egipto'],
            ['id' => 68, 'iso' => 'SV', 'nombre' => 'El Salvador'],
            ['id' => 69, 'iso' => 'AE', 'nombre' => 'Emiratos Árabes Unidos'],
            ['id' => 70, 'iso' => 'ER', 'nombre' => 'Eritrea'],
            ['id' => 71, 'iso' => 'SK', 'nombre' => 'Eslovaquia'],
            ['id' => 72, 'iso' => 'SI', 'nombre' => 'Eslovenia'],
            ['id' => 73, 'iso' => 'ES', 'nombre' => 'España'],
            ['id' => 74, 'iso' => 'UM', 'nombre' => 'Islas ultramarinas de Estados Unidos'],
            ['id' => 75, 'iso' => 'US', 'nombre' => 'Estados Unidos'],
            ['id' => 76, 'iso' => 'EE', 'nombre' => 'Estonia'],
            ['id' => 77, 'iso' => 'ET', 'nombre' => 'Etiopía'],
            ['id' => 78, 'iso' => 'FO', 'nombre' => 'Islas Feroe'],
            ['id' => 79, 'iso' => 'PH', 'nombre' => 'Filipinas'],
            ['id' => 80, 'iso' => 'FI', 'nombre' => 'Finlandia'],
            ['id' => 81, 'iso' => 'FJ', 'nombre' => 'Fiyi'],
            ['id' => 82, 'iso' => 'FR', 'nombre' => 'Francia'],
            ['id' => 83, 'iso' => 'GA', 'nombre' => 'Gabón'],
            ['id' => 84, 'iso' => 'GM', 'nombre' => 'Gambia'],
            ['id' => 85, 'iso' => 'GE', 'nombre' => 'Georgia'],
            ['id' => 86, 'iso' => 'GS', 'nombre' => 'Islas Georgias del Sur y Sandwich del Sur'],
            ['id' => 87, 'iso' => 'GH', 'nombre' => 'Ghana'],
            ['id' => 88, 'iso' => 'GI', 'nombre' => 'Gibraltar'],
            ['id' => 89, 'iso' => 'GD', 'nombre' => 'Granada'],
            ['id' => 90, 'iso' => 'GR', 'nombre' => 'Grecia'],
            ['id' => 91, 'iso' => 'GL', 'nombre' => 'Groenlandia'],
            ['id' => 92, 'iso' => 'GP', 'nombre' => 'Guadalupe'],
            ['id' => 93, 'iso' => 'GU', 'nombre' => 'Guam'],
            ['id' => 94, 'iso' => 'GT', 'nombre' => 'Guatemala'],
            ['id' => 95, 'iso' => 'GF', 'nombre' => 'Guayana Francesa'],
            ['id' => 96, 'iso' => 'GN', 'nombre' => 'Guinea'],
            ['id' => 97, 'iso' => 'GQ', 'nombre' => 'Guinea Ecuatorial'],
            ['id' => 98, 'iso' => 'GW', 'nombre' => 'Guinea-Bissau'],
            ['id' => 99, 'iso' => 'GY', 'nombre' => 'Guyana'],
            ['id' => 100, 'iso' => 'HT', 'nombre' => 'Haití'],
            ['id' => 101, 'iso' => 'HM', 'nombre' => 'Islas Heard y McDonald'],
            ['id' => 102, 'iso' => 'HN', 'nombre' => 'Honduras'],
            ['id' => 103, 'iso' => 'HK', 'nombre' => 'Hong Kong'],
            ['id' => 104, 'iso' => 'HU', 'nombre' => 'Hungría'],
            ['id' => 105, 'iso' => 'IN', 'nombre' => 'India'],
            ['id' => 106, 'iso' => 'ID', 'nombre' => 'Indonesia'],
            ['id' => 107, 'iso' => 'IR', 'nombre' => 'Irán'],
            ['id' => 108, 'iso' => 'IQ', 'nombre' => 'Iraq'],
            ['id' => 109, 'iso' => 'IE', 'nombre' => 'Irlanda'],
            ['id' => 110, 'iso' => 'IS', 'nombre' => 'Islandia'],
            ['id' => 111, 'iso' => 'IL', 'nombre' => 'Israel'],
            ['id' => 112, 'iso' => 'IT', 'nombre' => 'Italia'],
            ['id' => 113, 'iso' => 'JM', 'nombre' => 'Jamaica'],
            ['id' => 114, 'iso' => 'JP', 'nombre' => 'Japón'],
            ['id' => 115, 'iso' => 'JO', 'nombre' => 'Jordania'],
            ['id' => 116, 'iso' => 'KZ', 'nombre' => 'Kazajstán'],
            ['id' => 117, 'iso' => 'KE', 'nombre' => 'Kenia'],
            ['id' => 118, 'iso' => 'KG', 'nombre' => 'Kirguistán'],
            ['id' => 119, 'iso' => 'KI', 'nombre' => 'Kiribati'],
            ['id' => 120, 'iso' => 'KW', 'nombre' => 'Kuwait'],
            ['id' => 121, 'iso' => 'LA', 'nombre' => 'Laos'],
            ['id' => 122, 'iso' => 'LS', 'nombre' => 'Lesotho'],
            ['id' => 123, 'iso' => 'LV', 'nombre' => 'Letonia'],
            ['id' => 124, 'iso' => 'LB', 'nombre' => 'Líbano'],
            ['id' => 125, 'iso' => 'LR', 'nombre' => 'Liberia'],
            ['id' => 126, 'iso' => 'LY', 'nombre' => 'Libia'],
            ['id' => 127, 'iso' => 'LI', 'nombre' => 'Liechtenstein'],
            ['id' => 128, 'iso' => 'LT', 'nombre' => 'Lituania'],
            ['id' => 129, 'iso' => 'LU', 'nombre' => 'Luxemburgo'],
            ['id' => 130, 'iso' => 'MO', 'nombre' => 'Macao'],
            ['id' => 131, 'iso' => 'MK', 'nombre' => 'ARY Macedonia'],
            ['id' => 132, 'iso' => 'MG', 'nombre' => 'Madagascar'],
            ['id' => 133, 'iso' => 'MY', 'nombre' => 'Malasia'],
            ['id' => 134, 'iso' => 'MW', 'nombre' => 'Malawi'],
            ['id' => 135, 'iso' => 'MV', 'nombre' => 'Maldivas'],
            ['id' => 136, 'iso' => 'ML', 'nombre' => 'Malí'],
            ['id' => 137, 'iso' => 'MT', 'nombre' => 'Malta'],
            ['id' => 138, 'iso' => 'FK', 'nombre' => 'Islas Malvinas'],
            ['id' => 139, 'iso' => 'MP', 'nombre' => 'Islas Marianas del Norte'],
            ['id' => 140, 'iso' => 'MA', 'nombre' => 'Marruecos'],
            ['id' => 141, 'iso' => 'MH', 'nombre' => 'Islas Marshall'],
            ['id' => 142, 'iso' => 'MQ', 'nombre' => 'Martinica'],
            ['id' => 143, 'iso' => 'MU', 'nombre' => 'Mauricio'],
            ['id' => 144, 'iso' => 'MR', 'nombre' => 'Mauritania'],
            ['id' => 145, 'iso' => 'YT', 'nombre' => 'Mayotte'],
            ['id' => 146, 'iso' => 'MX', 'nombre' => 'México'],
            ['id' => 147, 'iso' => 'FM', 'nombre' => 'Micronesia'],
            ['id' => 148, 'iso' => 'MD', 'nombre' => 'Moldavia'],
            ['id' => 149, 'iso' => 'MC', 'nombre' => 'Mónaco'],
            ['id' => 150, 'iso' => 'MN', 'nombre' => 'Mongolia'],
            ['id' => 151, 'iso' => 'MS', 'nombre' => 'Montserrat'],
            ['id' => 152, 'iso' => 'MZ', 'nombre' => 'Mozambique'],
            ['id' => 153, 'iso' => 'MM', 'nombre' => 'Myanmar'],
            ['id' => 154, 'iso' => 'NA', 'nombre' => 'Namibia'],
            ['id' => 155, 'iso' => 'NR', 'nombre' => 'Nauru'],
            ['id' => 156, 'iso' => 'NP', 'nombre' => 'Nepal'],
            ['id' => 157, 'iso' => 'NI', 'nombre' => 'Nicaragua'],
            ['id' => 158, 'iso' => 'NE', 'nombre' => 'Níger'],
            ['id' => 159, 'iso' => 'NG', 'nombre' => 'Nigeria'],
            ['id' => 160, 'iso' => 'NU', 'nombre' => 'Niue'],
            ['id' => 161, 'iso' => 'NF', 'nombre' => 'Isla Norfolk'],
            ['id' => 162, 'iso' => 'NO', 'nombre' => 'Noruega'],
            ['id' => 163, 'iso' => 'NC', 'nombre' => 'Nueva Caledonia'],
            ['id' => 164, 'iso' => 'NZ', 'nombre' => 'Nueva Zelanda'],
            ['id' => 165, 'iso' => 'OM', 'nombre' => 'Omán'],
            ['id' => 166, 'iso' => 'NL', 'nombre' => 'Países Bajos'],
            ['id' => 167, 'iso' => 'PK', 'nombre' => 'Pakistán'],
            ['id' => 168, 'iso' => 'PW', 'nombre' => 'Palau'],
            ['id' => 169, 'iso' => 'PS', 'nombre' => 'Palestina'],
            ['id' => 170, 'iso' => 'PA', 'nombre' => 'Panamá'],
            ['id' => 171, 'iso' => 'PG', 'nombre' => 'Papúa Nueva Guinea'],
            ['id' => 172, 'iso' => 'PY', 'nombre' => 'Paraguay'],
            ['id' => 173, 'iso' => 'PE', 'nombre' => 'Perú'],
            ['id' => 174, 'iso' => 'PN', 'nombre' => 'Islas Pitcairn'],
            ['id' => 175, 'iso' => 'PF', 'nombre' => 'Polinesia Francesa'],
            ['id' => 176, 'iso' => 'PL', 'nombre' => 'Polonia'],
            ['id' => 177, 'iso' => 'PT', 'nombre' => 'Portugal'],
            ['id' => 178, 'iso' => 'PR', 'nombre' => 'Puerto Rico'],
            ['id' => 179, 'iso' => 'QA', 'nombre' => 'Qatar'],
            ['id' => 180, 'iso' => 'GB', 'nombre' => 'Reino Unido'],
            ['id' => 181, 'iso' => 'RE', 'nombre' => 'Reunión'],
            ['id' => 182, 'iso' => 'RW', 'nombre' => 'Ruanda'],
            ['id' => 183, 'iso' => 'RO', 'nombre' => 'Rumania'],
            ['id' => 184, 'iso' => 'RU', 'nombre' => 'Rusia'],
            ['id' => 185, 'iso' => 'EH', 'nombre' => 'Sahara Occidental'],
            ['id' => 186, 'iso' => 'SB', 'nombre' => 'Islas Salomón'],
            ['id' => 187, 'iso' => 'WS', 'nombre' => 'Samoa'],
            ['id' => 188, 'iso' => 'AS', 'nombre' => 'Samoa Americana'],
            ['id' => 189, 'iso' => 'KN', 'nombre' => 'San Cristóbal y Nevis'],
            ['id' => 190, 'iso' => 'SM', 'nombre' => 'San Marino'],
            ['id' => 191, 'iso' => 'PM', 'nombre' => 'San Pedro y Miquelón'],
            ['id' => 192, 'iso' => 'VC', 'nombre' => 'San Vicente y las Granadinas'],
            ['id' => 193, 'iso' => 'SH', 'nombre' => 'Santa Helena'],
            ['id' => 194, 'iso' => 'LC', 'nombre' => 'Santa Lucía'],
            ['id' => 195, 'iso' => 'ST', 'nombre' => 'Santo Tomé y Príncipe'],
            ['id' => 196, 'iso' => 'SN', 'nombre' => 'Senegal'],
            ['id' => 197, 'iso' => 'CS', 'nombre' => 'Serbia y Montenegro'],
            ['id' => 198, 'iso' => 'SC', 'nombre' => 'Seychelles'],
            ['id' => 199, 'iso' => 'SL', 'nombre' => 'Sierra Leona'],
            ['id' => 200, 'iso' => 'SG', 'nombre' => 'Singapur'],
            ['id' => 201, 'iso' => 'SY', 'nombre' => 'Siria'],
            ['id' => 202, 'iso' => 'SO', 'nombre' => 'Somalia'],
            ['id' => 203, 'iso' => 'LK', 'nombre' => 'Sri Lanka'],
            ['id' => 204, 'iso' => 'SZ', 'nombre' => 'Suazilandia'],
            ['id' => 205, 'iso' => 'ZA', 'nombre' => 'Sudáfrica'],
            ['id' => 206, 'iso' => 'SD', 'nombre' => 'Sudán'],
            ['id' => 207, 'iso' => 'SE', 'nombre' => 'Suecia'],
            ['id' => 208, 'iso' => 'CH', 'nombre' => 'Suiza'],
            ['id' => 209, 'iso' => 'SR', 'nombre' => 'Surinam'],
            ['id' => 210, 'iso' => 'SJ', 'nombre' => 'Svalbard y Jan Mayen'],
            ['id' => 211, 'iso' => 'TH', 'nombre' => 'Tailandia'],
            ['id' => 212, 'iso' => 'TW', 'nombre' => 'Taiwán'],
            ['id' => 213, 'iso' => 'TZ', 'nombre' => 'Tanzania'],
            ['id' => 214, 'iso' => 'TJ', 'nombre' => 'Tayikistán'],
            ['id' => 215, 'iso' => 'IO', 'nombre' => 'Territorio Británico del Océano Índico'],
            ['id' => 216, 'iso' => 'TF', 'nombre' => 'Territorios Australes Franceses'],
            ['id' => 217, 'iso' => 'TL', 'nombre' => 'Timor Oriental'],
            ['id' => 218, 'iso' => 'TG', 'nombre' => 'Togo'],
            ['id' => 219, 'iso' => 'TK', 'nombre' => 'Tokelau'],
            ['id' => 220, 'iso' => 'TO', 'nombre' => 'Tonga'],
            ['id' => 221, 'iso' => 'TT', 'nombre' => 'Trinidad y Tobago'],
            ['id' => 222, 'iso' => 'TN', 'nombre' => 'Túnez'],
            ['id' => 223, 'iso' => 'TC', 'nombre' => 'Islas Turcas y Caicos'],
            ['id' => 224, 'iso' => 'TM', 'nombre' => 'Turkmenistán'],
            ['id' => 225, 'iso' => 'TR', 'nombre' => 'Turquía'],
            ['id' => 226, 'iso' => 'TV', 'nombre' => 'Tuvalu'],
            ['id' => 227, 'iso' => 'UA', 'nombre' => 'Ucrania'],
            ['id' => 228, 'iso' => 'UG', 'nombre' => 'Uganda'],
            ['id' => 229, 'iso' => 'UY', 'nombre' => 'Uruguay'],
            ['id' => 230, 'iso' => 'UZ', 'nombre' => 'Uzbekistán'],
            ['id' => 231, 'iso' => 'VU', 'nombre' => 'Vanuatu'],
            ['id' => 232, 'iso' => 'VE', 'nombre' => 'Venezuela'],
            ['id' => 233, 'iso' => 'VN', 'nombre' => 'Vietnam'],
            ['id' => 234, 'iso' => 'VG', 'nombre' => 'Islas Vírgenes Británicas'],
            ['id' => 235, 'iso' => 'VI', 'nombre' => 'Islas Vírgenes de los Estados Unidos'],
            ['id' => 236, 'iso' => 'WF', 'nombre' => 'Wallis y Futuna'],
            ['id' => 237, 'iso' => 'YE', 'nombre' => 'Yemen'],
            ['id' => 238, 'iso' => 'DJ', 'nombre' => 'Yibuti'],
            ['id' => 239, 'iso' => 'ZM', 'nombre' => 'Zambia'],
            ['id' => 240, 'iso' => 'ZW', 'nombre' => 'Zimbabue']
        ]);
    }
}
